# Generated by Django 6.1 on 2026-08-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Current Semester', max_length=100)),
                ('start_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('date', 'timetable'), name='unique_attendance_per_lecture'),
        ),
    ]
